###
GET {{host}}/test/get
Authorization: eyJraWQiOiJDV1MiLCJhbGciOiJFUzI1NiJ9.eyJpc3MiOiJjb20ud29vZHkiLCJhdWQiOiJ5dW4tbWVuZy1zaG9wIiwic3ViIjoidG9tIiwiaWF0IjoxNjYwODczMjg5LCJleHAiOjE2NjYwNTcyODksImp0aSI6IjRiNjNlMmU5LTgzNGMtNGY3Yy1hYzMyLTE1ZDdhYzc1NjgxZiIsInVpZCI6IjgxMzkzOTYxOSJ9.Zv5Uaa5PdbBiMma0AFktxvuscyyOk8q15JlgatjL_dBk22l6snFjtQs_IULGOFyx0lxh_FsMPW7wigzMMhmrnA


###
GET {{host}}/user-service/haha/lala
Origin: https://docs.spring.io
Access-Control-Request-Headers: authorization
Access-Control-Request-Method: GET


###
OPTIONS {{host}}/ms-common/upload
Origin: https://docs.spring.io
Access-Control-Request-Headers: authorization
Access-Control-Request-Method: POST

###
GET {{host}}/test/get
Origin: https://docs.spring.io
#Access-Control-Request-Headers: authorization
#Access-Control-Request-Method: GET


###
GET https://httpbin.org/get
Origin: https://docs.spring.io

### 小程序账号登录
POST {{host}}/ms-user/o/api/login
Content-Type: application/json

{
  "userName": "13888888888",
  "password": "123456"
}

> {%
  client.global.set("auth_token", response.body.data.accessToken);
  client.global.set("refresh_token", response.body.data.refreshToken);

%}

### refreshToken
GET {{host}}/ms-user/o/api/refreshToken?refreshToken=745ebad5-a15e-4958-a9d0-ccc636f57484

###
GET {{host}}/ms-user/userLoginLog/10
Authorization: eyJraWQiOiJ3ZCIsImFsZyI6IkVTMjU2In0.eyJpc3MiOiJjb20ud29vZHkiLCJhdWQiOiJZVU5fTUVOR19NQSIsInN1YiI6InNodW4iLCJpYXQiOjE2NTc2MTI1NzMsImV4cCI6MTY1NzYxNDM3MywianRpIjoiYThjN2JjYWUtMjgxZS00NzU0LThmZjMtNjc0ZTJkZGMwOGMwIiwidWlkIjoxNDc4NTU3NTE2ODk5MTYwMDY0LCJlaWQiOjB9.wY3YlwNNa1En_P-zwVu_Zsl6W01mNIdgu_Qx8FS4GSmjY0iMmPaRY_I_pSCPzylzxDLJ6vSlWH6z0dJmJexDnQ

###
GET {{host}}/prod/prodShopAvailablePv?shopId=122&skuId=104749
#Authorization: eyJraWQiOiJDV1MiLCJhbGciOiJFUzI1NiJ9.eyJpc3MiOiJjb20ud29vZHkiLCJhdWQiOiJ5dW4tbWVuZy1zaG9wIiwic3ViIjoidG9tIiwiaWF0IjoxNjYwODczMjg5LCJleHAiOjE2NjYwNTcyODksImp0aSI6IjRiNjNlMmU5LTgzNGMtNGY3Yy1hYzMyLTE1ZDdhYzc1NjgxZiIsInVpZCI6IjgxMzkzOTYxOSJ9.Zv5Uaa5PdbBiMma0AFktxvuscyyOk8q15JlgatjL_dBk22l6snFjtQs_IULGOFyx0lxh_FsMPW7wigzMMhmrnA
Host: api.shwoody.com
